name: Testdata Lint Template

# Trigger the workflow on workflow caller
on:
  # reusable workflow template
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      working-directory:
        required: true
        type: string

jobs:
  check-testdata-lint:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Clone the code
        uses: actions/checkout@v3
      - name: Run linter for ${{ inputs.name }}
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
          working-directory: ${{ inputs.working-directory }}
          args: --issues-exit-code=0 # Only report warning but not block merge
          only-new-issues: true # Show only new issues if it's a pull request
      - name: Report failure
        uses: nashmaniac/create-issue-action@v1.1
        # Only report failures of pushes (PRs have are visible through the Checks section) to the default branch
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          title: 🐛 Lint failed for ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: kind/bug
          body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
